In [1]:
import torch 

In [2]:
conv = torch.nn.Conv2d(3, 512, 4, stride=4)
conv

Conv2d(3, 512, kernel_size=(4, 4), stride=(4, 4))

In [3]:
output = conv(torch.randn(16, 3, 32, 32)).reshape((16, 512, 64))
output.shape

torch.Size([16, 512, 64])

In [4]:
output = output.reshape((16, 512, 64))
output.shape

torch.Size([16, 512, 64])

In [5]:
output = torch.transpose(output, 1, 2)
output.shape

torch.Size([16, 64, 512])

In [6]:
torch.cat((output, torch.nn.Parameter(torch.randn(16, 1, 512))), dim=1).shape

torch.Size([16, 65, 512])

In [7]:
positional_embeddings = torch.nn.Parameter(torch.randn(1, 65, 512))
positional_embeddings.shape

torch.Size([1, 65, 512])

In [8]:
inputs = torch.randn(256, 65, 512)
inputs.shape

torch.Size([256, 65, 512])

In [9]:
outputs = inputs + positional_embeddings
outputs.shape

torch.Size([256, 65, 512])

In [10]:
positional_embeddings[0][0][0], inputs[0][0][0], outputs[0][0][0]

(tensor(-1.2371, grad_fn=<SelectBackward0>),
 tensor(0.8575),
 tensor(-0.3796, grad_fn=<SelectBackward0>))

In [11]:
layer_norm = torch.nn.LayerNorm(512)

inputs = torch.randn(256, 65, 512)

layer_norm(inputs).shape

torch.Size([256, 65, 512])

In [17]:
Q_linear_transform = torch.nn.Linear(512, 128, bias=False)
K_linear_transform = torch.nn.Linear(512, 128, bias=False)

In [19]:
inputs = torch.randn(256, 65, 512)
Q = Q_linear_transform(inputs)
K = K_linear_transform(inputs)
Q.shape, K.shape

(torch.Size([256, 65, 128]), torch.Size([256, 65, 128]))

In [27]:
import math

output = (Q @ K.transpose(-2, -1)) / math.sqrt(128)
output.shape

torch.Size([256, 65, 65])

In [31]:
from torch.nn.functional import softmax

softmax(output, dim=-1)

tensor([[[0.0236, 0.0159, 0.0292,  ..., 0.0128, 0.0170, 0.0090],
         [0.0182, 0.0195, 0.0125,  ..., 0.0103, 0.0149, 0.0174],
         [0.0176, 0.0198, 0.0085,  ..., 0.0218, 0.0273, 0.0140],
         ...,
         [0.0131, 0.0117, 0.0136,  ..., 0.0135, 0.0077, 0.0200],
         [0.0132, 0.0125, 0.0198,  ..., 0.0154, 0.0088, 0.0217],
         [0.0140, 0.0213, 0.0089,  ..., 0.0108, 0.0108, 0.0385]],

        [[0.0083, 0.0140, 0.0106,  ..., 0.0290, 0.0189, 0.0154],
         [0.0096, 0.0112, 0.0149,  ..., 0.0125, 0.0088, 0.0165],
         [0.0209, 0.0178, 0.0143,  ..., 0.0187, 0.0142, 0.0282],
         ...,
         [0.0130, 0.0174, 0.0139,  ..., 0.0150, 0.0112, 0.0203],
         [0.0178, 0.0206, 0.0203,  ..., 0.0098, 0.0176, 0.0121],
         [0.0070, 0.0211, 0.0139,  ..., 0.0179, 0.0180, 0.0091]],

        [[0.0108, 0.0213, 0.0205,  ..., 0.0216, 0.0182, 0.0231],
         [0.0084, 0.0160, 0.0188,  ..., 0.0188, 0.0189, 0.0082],
         [0.0218, 0.0124, 0.0090,  ..., 0.0145, 0.0164, 0.

In [32]:
head_1 = torch.randn(256, 65, 128)
head_2 = torch.randn(256, 65, 128)
head_3 = torch.randn(256, 65, 128)
head_4 = torch.randn(256, 65, 128)

In [33]:
output = torch.cat((head_1, head_2, head_3, head_4), dim=-1)
output.shape

torch.Size([256, 65, 512])

In [37]:
HEADS = 8

In [38]:
self_attention_heads = [torch.nn.Identity() for _ in range(HEADS)]
self_attention_heads

[Identity(),
 Identity(),
 Identity(),
 Identity(),
 Identity(),
 Identity(),
 Identity(),
 Identity()]

In [55]:
inputs = torch.randn(256, 65, 512)

In [59]:
inputs[1][0]

tensor([-2.9795e-01,  3.4942e-01,  1.0613e+00,  4.9708e-02,  6.5685e-01,
        -4.8043e-01,  4.3098e-01, -1.2163e+00, -2.2672e+00,  3.1443e-01,
         5.4613e-03,  7.5140e-01, -9.7392e-01, -1.4761e+00, -1.1964e+00,
         9.2728e-04,  6.7204e-01,  1.0241e+00,  1.2799e+00, -3.9876e-02,
        -9.2407e-01, -1.2171e+00,  1.2391e+00,  1.6666e+00, -9.0154e-01,
        -1.7071e+00,  8.5638e-02, -1.4195e+00,  6.3986e-01,  1.1939e+00,
        -2.1258e+00, -1.9139e-01, -1.4033e+00, -2.3368e-01,  4.5924e-01,
        -1.1760e+00,  2.9709e+00,  2.2232e+00,  1.3688e+00, -8.8236e-01,
        -4.2601e-01,  8.7250e-01,  1.0210e-01,  2.0676e+00, -1.3257e-01,
        -1.7816e+00,  7.1272e-01, -3.8961e-01,  4.1667e-01, -8.0699e-01,
         5.1026e-01,  2.8126e-01, -4.5182e-01, -9.8436e-02,  3.6319e-01,
        -3.2373e-01, -1.1552e+00,  2.8438e+00,  1.6153e+00,  1.6112e-01,
         3.7578e-01, -2.4693e-01, -1.3996e+00,  1.4904e-01,  8.6770e-01,
         2.0150e+00,  4.7559e-01, -3.6450e-01, -2.0

In [57]:
outputs = torch.select(inputs, -2, 0).reshape(256, 1, 512)
outputs.shape

torch.Size([256, 1, 512])

In [60]:
outputs[1][0]

tensor([-2.9795e-01,  3.4942e-01,  1.0613e+00,  4.9708e-02,  6.5685e-01,
        -4.8043e-01,  4.3098e-01, -1.2163e+00, -2.2672e+00,  3.1443e-01,
         5.4613e-03,  7.5140e-01, -9.7392e-01, -1.4761e+00, -1.1964e+00,
         9.2728e-04,  6.7204e-01,  1.0241e+00,  1.2799e+00, -3.9876e-02,
        -9.2407e-01, -1.2171e+00,  1.2391e+00,  1.6666e+00, -9.0154e-01,
        -1.7071e+00,  8.5638e-02, -1.4195e+00,  6.3986e-01,  1.1939e+00,
        -2.1258e+00, -1.9139e-01, -1.4033e+00, -2.3368e-01,  4.5924e-01,
        -1.1760e+00,  2.9709e+00,  2.2232e+00,  1.3688e+00, -8.8236e-01,
        -4.2601e-01,  8.7250e-01,  1.0210e-01,  2.0676e+00, -1.3257e-01,
        -1.7816e+00,  7.1272e-01, -3.8961e-01,  4.1667e-01, -8.0699e-01,
         5.1026e-01,  2.8126e-01, -4.5182e-01, -9.8436e-02,  3.6319e-01,
        -3.2373e-01, -1.1552e+00,  2.8438e+00,  1.6153e+00,  1.6112e-01,
         3.7578e-01, -2.4693e-01, -1.3996e+00,  1.4904e-01,  8.6770e-01,
         2.0150e+00,  4.7559e-01, -3.6450e-01, -2.0